services:
  nacos:
    image: nacos/nacos-server:v2.2.3-slim
    container_name: leasego-nacos
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"
    restart: always
    volumes:
      - ${DOCKER_DATA_PATH}/nacos:/home/nacos/data
  mysql-db:
    image: mysql:8.0
    container_name: leasego-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=lease
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ${DOCKER_DATA_PATH}/mysql:/var/lib/mysql
  minio:
    image: minio/minio
    container_name: leasego-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - ${DOCKER_DATA_PATH}/minio
    command: server /data --console-address ":9001"
    restart: always
  redis:
    image: redis/redis-stack:7.4.0-v1
    container_name: leasego-redis
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ${DOCKER_DATA_PATH}/redis
    environment:
      - REDIS_ARGS=--appendonly yes
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: leasego-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ${DOCKER_DATA_PATH}/rabbitmq:/var/lib/rabbitmq
  sentinel-dashboard:
    build:
      context: ./init/sentinel
      dockerfile: Dockerfile
    image: leasego/sentinel-dashboard:1.8.6
    container_name: leasego-sentinel
    ports:
      - "8858:8080"
    restart: always
    environment:
      SENTINEL_DASHBOARD_USERNAME: ${SENTINEL_DASHBOARD_USERNAME}
      SENTINEL_DASHBOARD_PASSWORD: ${SENTINEL_DASHBOARD_PASSWORD}
