server:
  port: 8082

spring:
  application:
    name: chat-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:public}
      config:
        import-check:
          enabled: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3307}/lease?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}

  cloud:
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD:127.0.0.1:8858}
        client-ip: 127.0.0.1
      eager: true
      filter:
        enabled: true

springdoc:
  api-docs:
    path: /chat-service-docs

# WebSocket配置
websocket:
  endpoint: /app/chat

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
